=== tada195908/tada195908.github.io/xml/Jarticle.dtd
<!ELEMENT Jarticle (Title,Subtitle?,Author?,Date?,link?,Section*)>
<!ELEMENT Title ANY>
<!ELEMENT Subtitle ANY>
<!ELEMENT Author ANY>
<!ATTLIST Author Institute CDATA #IMPLIED
                 Email     CDATA #IMPLIED
                 EmailImg  CDATA #IMPLIED>

<!ELEMENT link EMPTY>
<!ATTLIST link href CDATA #IMPLIED
               rel  CDATA #IMPLIED>
<!ELEMENT Section (div|Subsection*)>
<!ATTLIST Section Title CDATA #IMPLIED>

<!ELEMENT Subsection (div)>
<!ATTLIST Subsection Title CDATA #IMPLIED>
<!ELEMENT div ANY>
<!ELEMENT Text ANY>
<!ELEMENT p ANY>
<!ELEMENT ul (li+)>
<!ELEMENT ol (li+)>
<!ELEMENT dl (dt,dd)+>
<!ELEMENT li ANY>
<!ELEMENT dt ANY>
<!ELEMENT dd ANY>

<!ELEMENT pre (#PCDATA)>
<!ELEMENT quote ANY>
<!ELEMENT Figure (Caption?,img?)>
<!ATTLIST Figure Label CDATA #IMPLIED>
<!ELEMENT Table (TableHeader?,TableBody?,Caption?)>
<!ATTLIST Table  Label CDATA #IMPLIED>
<!ELEMENT TableHeader (tr)>
<!ELEMENT TableBody (tr*)>
<!ELEMENT tr (td|th)*>
<!ELEMENT td ANY>
<!ELEMENT th ANY>
<!ELEMENT Caption (#PCDATA)>
<!ELEMENT img EMPTY>
<!ATTLIST img src CDATA #REQUIRED
              alt CDATA #REQUIRED
              width CDATA #IMPLIED
              height CDATA #IMPLIED
              altwidth CDATA #IMPLIED>

<!ELEMENT applet (param*)>
<!ATTLIST applet archive CDATA #IMPLIED
                 code    CDATA #REQUIRED
                 width   CDATA #IMPLIED
                 height  CDATA #IMPLIED>
<!ELEMENT param EMPTY>
<!ATTLIST param name CDATA #REQUIRED
                value CDATA #IMPLIED>

<!ELEMENT a ANY>
<!ATTLIST a href CDATA #REQUIRED>
<!ELEMENT b ANY>
<!ELEMENT i ANY>
<!ELEMENT tt ANY>
<!ELEMENT Date ANY>

=== tada195908/tada195908.github.io/lecture/ObjectOrientedProgramming/index.2018.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Jarticle SYSTEM "/xml/Jarticle.dtd">
<?xml-stylesheet type="text/xsl" href="/xml/Jarticle.xsl"?>
<Jarticle>
    <Title>オブジェクト指向プログラミング特論(Object-oriented Programming)</Title>
    <Subtitle>2018年度</Subtitle>
    <link rel="stylesheet" href="../lecture.css"/>
    <Author Institute="佐賀大学工学系研究科" EmailImg="/images/address.gif">只木進一
    </Author>
    <Section Title="概要">
        <div>
            <p>
情報処理システムが扱い対象をデータとその操作が組となったオブジェクトとして扱うプログラミングの
枠組みをオブジェクト指向プログラミングと言う。現実の動きとの対応付けが容易であることが利点である。
それだけでなく、プログラム要素の抽象化、それによる再利用可能性など、プログラム開発の効率化にも寄与する。
            </p>
            <p>
本講義では、Javaを使ったオブジェクト指向プログラミングを、実用的なプログラムを例にとりながら講義する。
また、抽象化や再利用の効率を上げるためのデザインパターンについても論じる。
            </p>
            <p>サンプルのソースコード中の日本語ははUTF-8です。Java8を想定しています。</p>
        </div>
    </Section>
    <Section Title="内容">
        <div>
            <ul>
                <li>
                    <a href="2018/pdf/Introduction.pdf">序論：講義の目的</a>
                </li>
                <li>
                    <a href="2018/pdf/Interface.pdf">インターフェースの利用</a>
                </li>
                <li>
                    <a href="2018/pdf/Superclass.pdf">抽象クラスの抽出</a>
                </li>
                <li><a href="2018/pdf/ThreadsAndRunnable.pdf">ThreadとRunnable</a></li>
                <li><a href="2018/pdf/CollectionsAndLamdaExpressions.pdf">CollectionとLambda式</a></li>
                <li><a href="2018/pdf/StringsAndRegularExpressions.pdf">文字列操作と正規表現</a></li>
				<li><a href ="2018/pdf/FilIO.pdf">File IOと例外処理</a></li>
				<li><a href="2018/pdf/URL.pdf">URL IO</a></li>
				<li><a href="2018/pdf/GUI1.pdf">Graphical User Interface - widgetを使う - </a></li>
				<li><a href="2018/pdf/Event.pdf">Eventとその処理</a></li>
				<li><a href="2018/pdf/GUI2.pdf">Graphical User Interface - 描画する - </a></li>
				<li><a href="2018/pdf/GraphSearch.pdf">Graphの探索</a></li>
                <li><a href="2018/javasrc/MyLib.tar.gz">MyLib</a></li>
            </ul>
        </div>
    </Section>
    <Section Title="レポート課題">
        <div>
            <ul>
                <li>
                    <a href="Reports/2016Final.pdf">2016年度課題期末</a>
                </li>
                <li>
                    <a href="Reports/2016.pdf">2016年度課題中間</a>
                </li>
                <li>
                    <a href="Reports/2010.pdf">2010年度課題</a>
                </li>
                <li>
                    <a href="Reports/2008.pdf">2008年度課題</a>
                </li>
            </ul>
        </div>
    </Section>
</Jarticle>

=== tada195908/tada195908.github.io/lecture/ObjectOrientedProgramming/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Jarticle SYSTEM "/xml/Jarticle.dtd">
<?xml-stylesheet type="text/xsl" href="/xml/Jarticle.xsl"?>
<Jarticle>
    <Title>オブジェクト指向プログラミング特論(Object-oriented Programming)</Title>
    <Subtitle>2024年度</Subtitle>
    <link rel="stylesheet" href="../lecture.css"/>
    <Author Institute="佐賀大学理工学研究科" EmailImg="/images/address.gif">只木進一
    </Author>
    <Section Title="概要">
        <div>
            <p>
情報処理システムが扱い対象をデータとその操作が組となったオブジェクトとして扱うプログラミングの
枠組みをオブジェクト指向プログラミングと言う。現実の動きとの対応付けが容易であることが利点である。
それだけでなく、プログラム要素の抽象化、それによる再利用可能性など、プログラム開発の効率化にも寄与する。
            </p>
            <p>
本講義では、Javaを使ったオブジェクト指向プログラミングを、実用的なプログラムを例にとりながら講義する。
また、抽象化や再利用の効率を上げるためのデザインパターンについても論じる。
            </p>
            <p>サンプルのソースコード中の日本語ははUTF-8です。Java17を想定しています。</p>
        </div>
    </Section>
    <Section Title="内容">
        <div>
            <ol>
                <li>
                    <a href="pdf/01_Introduction.pdf">序論：講義の目的</a><br/>
                    <a href="https://github.com/oop-mc-saga/Sort">
                    https://github.com/oop-mc-saga/Sort</a>
                </li>
                <li>
                    <a href="pdf/02_Interfaces.pdf">インターフェースの利用</a>
                </li>
                <li>
                    <a href="pdf/03_Superclasses.pdf">抽象クラスの抽出</a>
                </li>
                <li><a href="pdf/04_ThreadsAndRunnable.pdf">ThreadとRunnable</a><br/>
                <a href="https://github.com/oop-mc-saga/Thread">
                https://github.com/oop-mc-saga/Thread</a>
                </li>
                <li><a href="pdf/05_CollectionsAndLamdaExpressions.pdf">CollectionとLambda式</a><br/>
                <a href="https://github.com/oop-mc-saga/Lambda">
                https://github.com/oop-mc-saga/Lambda</a>
                </li>
                <li><a href="pdf/06_StringsAndRegularExpressions.pdf">文字列操作と正規表現</a><br/>
                <a href="https://github.com/oop-mc-saga/StringsAndRegularExpressions">
                https://github.com/oop-mc-saga/StringsAndRegularExpressions</a>
                </li>
                <li><a href="pdf/07_Midterm_report.pdf">中間レポート</a></li>
				<li><a href ="pdf/08_FileIO.pdf">File IOと例外処理</a><br/>
                <a href="https://github.com/oop-mc-saga/FileIOExamples">
                https://github.com/oop-mc-saga/FileIOExamples</a>
				</li>
				<li><a href="pdf/09_GUI1.pdf">Graphical User Interface - widgetを使う - </a><br/>
                <a href="https://github.com/oop-mc-saga/GUI1">
                https://github.com/oop-mc-saga/GUI1</a>
				</li>
				<li><a href="pdf/10_GUI2.pdf">Graphical User Interface - widgetを使う2 - </a>
				</li>
				<li><a href="pdf/11_Event.pdf">Eventとその処理</a><br/>
				<a href="https://github.com/oop-mc-saga/ColorChoice">
                https://github.com/oop-mc-saga/ColorChoice</a>
				</li>
				<li><a href="pdf/12_GUI3.pdf">Graphical User Interface - 描画する - </a><br/>
				<a href="https://github.com/oop-mc-saga/GUI2">
                https://github.com/oop-mc-saga/GUI2</a>				
				</li>
                <li><a href="pdf/13_Fractals.pdf">例: Fractals</a><br/>
                <a href="https://github.com/oop-mc-saga/Fractal">
                https://github.com/oop-mc-saga/Fractal</a>
                </li>
            </ol>
        </div>
<!--
        準備中
        <div>
            <ul>
            </ul>
        </div>
        -->
    </Section>

</Jarticle>

=== tada195908/tada195908.github.io/lecture/ObjectOrientedProgramming/index-2010.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Jarticle SYSTEM "/xml/Jarticle.dtd">
<?xml-stylesheet type="text/xsl" href="/xml/Jarticle.xsl"?>
<Jarticle>
    <Title>オブジェクト指向プログラミング特論(Object-oriented Programming)</Title>
    <Subtitle>2010年度</Subtitle>
    <link rel="stylesheet" href="../lecture.css"/>
    <Author Institute="佐賀大学総合情報基盤センター" EmailImg="/images/address.gif">只木進一
    </Author>
    <Section Title="概要">
        <div>
            <p>
情報処理システムが扱い対象をデータとその操作が組となったオブジェクトとして扱うプログラミングの
枠組みをオブジェクト指向プログラミングと言う。現実の動きとの対応付けが容易であることが利点である。
それだけでなく、プログラム要素の抽象化、それによる再利用可能性など、プログラム開発の効率化にも寄与する。
            </p>
            <p>
本講義では、Javaを使ったオブジェクト指向プログラミングを、実用的なプログラムを例にとりながら講義する。
また、抽象化や再利用の効率を上げるためのデザインパターンについても論じる。
            </p>
            <p>サンプルのソースコード中の日本語ははUTF-8です。</p>
            <p>順次、2010年度版に入れ替え作業中</p>
        </div>
    </Section>
    <Section Title="内容">
        <div>
            <ul>
                <li>
                    <a href="2010/pdf.2010/Introduction.pdf">序論：講義の目的
                    </a>
                </li>
                <li>
                    <a href="2010/pdf.2010/NetBeans.pdf">NetBeansの導入
                    </a>
                    [<a href="2010/pdf.2010/Exercises/SimpleJava.pdf">課題</a>]
                </li>
                <li>
                    <a href="2010/pdf.2010/SimpleJavaExample.pdf">Java入門
                    </a>
                    [<a href="2010/pdf.2010/Exercises/SimpleJava2.pdf">課題</a>]</li>
                <li>
<a href="2010/pdf.2010/SimpleJavaExample2.pdf">Java入門2
                    </a>
                    <a href="2010/javasrc.2010/SimplestSample/firstSample/NoClass.java">NoClass.java
                    </a>
                    <a href="2010/javasrc.2010/SimplestSample/firstSample/WithClass.java">WithClass.java
                    </a>
                    <a href="2010/javasrc.2010/SimplestSample/firstSample/Entry.java">Entry.java
                    </a>
                    <a href="2010/javasrc.2010/SimplestSample/firstSample/WithClassNew.java">WithClassNew.java
                    </a>
                    <a href="2010/javasrc.2010/SimplestSample/firstSample/EntryNew.java">EntryNew.java
                    </a>
                </li>
                <li>
                    <a href="2010/pdf.2010/WhatIsOOP.pdf">オブジェクト指向の基本的考え方
                    </a>
                </li>
                <li>
                  <a href="2010/pdf.2010/JavaFeatures.pdf">Java活用</a>
                  [<a href="2010/pdf.2010/Exercises/SimpleJava3.pdf">課題</a>]
                  <br/>
                  [<a href="2010/javasrc.2010/SimplestSample/secondSample/EntryNew.java">Entry.java</a>
                  <a href="2010/javasrc.2010/SimplestSample/secondSample/WithClassNew.java">WithClassNew.java</a>]<br/>
                  [<a href="2010/javasrc.2010/SimpestSample/thirdSample/WithAbstractEntry.java">WithAbstractEntry.java</a>
                  <a href="2010/javasrc.2010/SimpestSample/thirdSample/AbstractEntry.java">AbstractEntry.java</a>
                  [<a href="2010/javasrc.2010/SimpestSample/thirdSample/EntryOne.java">EntryOne.java</a>]
                </li>
                <li><a href="2010/pdf.2010/Inheritance.pdf">クラスの階層、継承</a>
                <br/>
                [<a href="2010/javasrc.2010/SimplestSample/universityMembers/Member.java">Member.java</a>
                 <a href="2010/javasrc.2010/SimplestSample/universityMembers/Student.java">Student.java</a>
                 <a href="2010/javasrc.2010/SimplestSample/universityMembers/Period.java">Period.java</a>]
                [<a href="2010/javasrc.2010/SimplestSample/thread/Runner.java">Runner.java</a>]
                </li>
                <li><a href="2010/pdf.2010/FileIO.pdf">File IO</a><br/>
                [<a href="2010/javasrc.2010/FileIOsamples/standardIO/IOMain.java">IOMain.java</a>
                 <a href="2010/javasrc.2010/FileIOSamples/FileIO/FileIOMain.java">FileIOMain.java</a>]
                </li>
                <li><a href="2010/pdf.2010/GUI1.pdf">Graphical User Interface:widgetを使う</a>
                [<a href="2010/pdf.2010/Exercises/SimpleTimer.pdf">課題</a>]
                <br/>
 		[
		<a href="2010/javasrc.2010/SampleGUI/guiWithoutAction/MainFrame.java">guiWithoutAction/MainFrame.java</a>
		<a href="2010/javasrc.2010/SampleGUI/guiWithoutAction/MainFrame.form">guiWithoutAction/MainFrame.form</a>
		<a href="2010/javasrc.2010/SampleGUI/guiWithAction/MainFrame.java">guiWithAction/MainFrame.java</a>
		<a href="2010/javasrc.2010/SampleGUI/guiWithAction/MainFrame.form">guiWithtAction/MainFrame.form</a>
                <a href="2010/javasrc.2010/SampleGUI/fileChooser/FileChooserMain.java">fileChooser/FileChooserMain.java</a>
                <a href="2010/javasrc.2010/SampleGUI/fileChooser/FileChooserMain.form">fileChooser/FileChooserMain.form</a>
                <a href="2010/javasrc.2010/SampleGUI/fileChooser/FileUtil.java">fileChooser/FileUtil.java</a>
		]<br/>
                [課題コード
                <a href="2010/javasrc.2010/SampleGUI/simpleTimer/Timer.java">simpleTimer/Timer.java</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleTimer/SimpleTimer.java">simpleTimer/SimpleTimer.java</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleTimer/SimpleTimer.form">simpleTimer/SimpleTimer.form</a>
                ]
                </li>
                <li><a href="2010/pdf.2010/GUI2.pdf">Graphical User Interface:描画する</a><br/>
                [<a href="2010/pdf.2010/Exercises/SimpleSquareDrawer.pdf">課題</a>]
                <br/>
                [
                <a href="2010/javasrc.2010/SampleGUI/shapeSamples/ShapeSamplesMain.java">shapeSamples/ShapeSamplesMain.java</a>
                <a href="2010/javasrc.2010/SampleGUI/shapeSamples/ShapeSamplesMain.form">shapeSamples/ShapeSamplesMain.form</a>
                <a href="2010/javasrc.2010/SampleGUI/shapeSamples/DrawPanel.java">shapeSamples/DrawPanel.java</a>
                <a href="2010/javasrc.2010/SampleGUI/shapeSamples/DrawPanel.form">shapeSamples/DrawPanel.form</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleDrawer/SimpleDrawerMain.java">simpleDrawer/SimpleDrawerMain.java</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleDrawer/SimpleDrawerMain.form">simpleDrawer/SimpleDrawerMain.form</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleDrawer/DrawPanel.java">simpleDrawer/DrawPanel.java</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleDrawer/DrawPanel.form">simpleDrawer/DrawPanel.form</a>
                ]<br/>
                [課題コード
                <a href="2010/javasrc.2010/SampleGUI/simpleSquareDrawer/SimpleSquareDrawerMain.java"> SimpleSquareDrawerMain.java</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleSquareDrawer/SimpleSquareDrawerMain.form"> SimpleSquareDrawerMain.form</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleSquareDrawer/DrawPanel.java">DrawPanel.java</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleSquareDrawer/DrawPanel.form">DrawPanel.form</a>
                <a href="2010/javasrc.2010/SampleGUI/simpleSquareDrawer/MyShape.java">MyShape.java</a>
                ]</li>
                <li><a href="2010/pdf.2010/CMOV.pdf">
                例：結合写像型最適速度交通流モデルのシミュレーション</a>
                [<a href="2010/javasrc.2010/CMOV.tar.gz">ソースコード</a>]</li>
                <li><a href="2010/pdf.2010/SimpleRandomWalk.pdf">
                例：簡単な酔歩シミュレーション</a>
                [<a href="2010/javasrc.2010/SimpleRandomWalk.tar.gz">ソースコード</a>]
                </li>
                <li><a href="2010/pdf.2010/DB.pdf">データベースの利用</a>
                [<a href="2010/javasrc.2010/DBSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2010/pdf.2010/XML.pdf">XMLの利用</a>
                [<a href="2010/javasrc.2010/XMLSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2010/pdf.2010/DB.pdf">データベースの利用</a>
                [<a href="2010/javasrc.2010/DBSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2010/pdf.2010/Servlet.pdf">サーブレット</a>
                [<a href="2010/javasrc.2010/ServletSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2010/pdf.2010/summary.pdf">まとめ</a></li>
            </ul>
        </div>
    </Section>
    <Section Title="レポート課題">
        <div>
          <ul>
            <li><a href="Reports/2010.pdf">2010年度課題</a></li>
            <li><a href="Reports/2008.pdf">2008年度課題</a></li>
          </ul>
        </div>
    </Section>
</Jarticle>

=== tada195908/tada195908.github.io/lecture/ObjectOrientedProgramming/index.2012.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE Jarticle SYSTEM "/xml/Jarticle.dtd">
<?xml-stylesheet type="text/xsl" href="/xml/Jarticle.xsl"?>
<Jarticle>
    <Title>オブジェクト指向プログラミング特論(Object-oriented Programming)</Title>
    <Subtitle>2014年度(更新中)</Subtitle>
    <link rel="stylesheet" href="../lecture.css"/>
    <Author Institute="佐賀大学工学系研究科" EmailImg="/images/address.gif">只木進一
    </Author>
    <Section Title="概要">
        <div>
            <p>
情報処理システムが扱い対象をデータとその操作が組となったオブジェクトとして扱うプログラミングの
枠組みをオブジェクト指向プログラミングと言う。現実の動きとの対応付けが容易であることが利点である。
それだけでなく、プログラム要素の抽象化、それによる再利用可能性など、プログラム開発の効率化にも寄与する。
            </p>
            <p>
本講義では、Javaを使ったオブジェクト指向プログラミングを、実用的なプログラムを例にとりながら講義する。
また、抽象化や再利用の効率を上げるためのデザインパターンについても論じる。
            </p>
            <p>サンプルのソースコード中の日本語ははUTF-8です。</p>
            <p>順次、2012年度版に入れ替え作業中</p>
        </div>
    </Section>
    <Section Title="内容">
        <div>
            <ul>
                <li>
                    <a href="2012/pdf.2012/Introduction.pdf">序論：講義の目的
                    </a>
                </li>
                <li>
                    <a href="2012/pdf.2012/NetBeans.pdf">NetBeansの導入</a>
<!--                    <a href="javasrc/SimplestSample/firstSample/NoClass.java">NoClass.java</a>
                    [<a href="2012/pdf.2012/Exercises/SimpleJava.pdf">課題</a>]
-->
              </li>
                <li>
                    <a href="2012/pdf.2012/SimpleJavaExample.pdf">Java入門</a>
                <li>
                    <a href="2012/pdf.2012/SimpleJavaExample2.pdf">Java入門2</a>
                    <!--
                    <a href="javasrc/SimplestSample/firstSample/WithClass.java">WithClass.java</a>
                    <a href="javasrc/SimplestSample/firstSample/Entry.java">Entry.java</a>
                    <a href="javasrc/SimplestSample/firstSample/WithClassNew.java">WithClassNew.java</a>
                    <a href="javasrc/SimplestSample/firstSample/EntryNew.java">EntryNew.java</a>
                    [<a href="2012/pdf.2012/Exercises/SimpleJava2.pdf">課題</a>]-->
</li>
                </li>
                <li>
                  <a href="2012/pdf.2012/JavaFeatures.pdf">Java活用</a>
<!--                  [<a href="2012/pdf.2012/Exercises/SimpleJava3.pdf">課題</a>]-->
                  <br/>
                  [<a href="javasrc/SimplestSample/secondSample/EntryNew.java">Entry.java</a>
                  <a href="javasrc/SimplestSample/secondSample/WithClassNew.java">WithClassNew.java</a>]<br/>
                  [<a href="javasrc/SimpestSample/thirdSample/WithAbstractEntry.java">WithAbstractEntry.java</a>
                  <a href="javasrc/SimpestSample/thirdSample/AbstractEntry.java">AbstractEntry.java</a>
                  [<a href="javasrc/SimpestSample/thirdSample/EntryOne.java">EntryOne.java</a>]
                </li>
                <li>
                    <a href="2012/pdf.2012/WhatIsOOP.pdf">オブジェクト指向の基本的考え方</a>
                </li>
                <li><a href="2012/pdf.2012/Inheritance.pdf">クラスの階層、継承</a>
                <br/>
                [<a href="javasrc/SimplestSample/universityMembers/Member.java">Member.java</a>
                 <a href="javasrc/SimplestSample/universityMembers/Student.java">Student.java</a>
                 <a href="javasrc/SimplestSample/universityMembers/Period.java">Period.java</a>]
                [<a href="javasrc/SimplestSample/thread/Runner.java">Runner.java</a>]
                </li>
                <li><a href="2012/pdf.2012/FileIO.pdf">File IO</a><br/>
                [<a href="javasrc/FileIOsamples/standardIO/IOMain.java">IOMain.java</a>
                 <a href="javasrc/FileIOSamples/FileIO/FileIOMain.java">FileIOMain.java</a>]
                </li>
                <li><a href="2012/pdf.2012/GUI1.pdf">Graphical User Interface:widgetを使う</a>
<!--                [<a href="2012/pdf.2012/Exercises/SimpleTimer.pdf">課題</a>]-->
                <br/>
 		[
		<a href="javasrc/SampleGUI/guiWithoutAction/MainFrame.java">guiWithoutAction/MainFrame.java</a>
		<a href="javasrc/SampleGUI/guiWithoutAction/MainFrame.form">guiWithoutAction/MainFrame.form</a>
		<a href="javasrc/SampleGUI/guiWithAction/MainFrame.java">guiWithAction/MainFrame.java</a>
		<a href="javasrc/SampleGUI/guiWithAction/MainFrame.form">guiWithtAction/MainFrame.form</a>
                <a href="javasrc/SampleGUI/fileChooser/FileChooserMain.java">fileChooser/FileChooserMain.java</a>
                <a href="javasrc/SampleGUI/fileChooser/FileChooserMain.form">fileChooser/FileChooserMain.form</a>
                <a href="javasrc/SampleGUI/fileChooser/FileUtil.java">fileChooser/FileUtil.java</a>
		]<br/>
                [課題コード
                <!--
                <a href="javasrc/SampleGUI/simpleTimer/Timer.java">simpleTimer/Timer.java</a>
                <a href="javasrc/SampleGUI/simpleTimer/SimpleTimer.java">simpleTimer/SimpleTimer.java</a>
                <a href="javasrc/SampleGUI/simpleTimer/SimpleTimer.form">simpleTimer/SimpleTimer.form</a>
                <a href="javasrc/SampleGUI/simpleTimer/SetTimePanel.java">simpleTimer/SetTimePanel.java</a>
                <a href="javasrc/SampleGUI/simpleTimer/SetTimePanel.form">simpleTimer/SetTimePanel.form</a>
                -->
                ]
                </li>
                <li><a href="2012/pdf.2012/GUI2.pdf">Graphical User Interface:描画する</a><br/>
                [<a href="2012/pdf.2012/Exercises/SimplePlotter.pdf">課題</a>
                (<a href="2012/pdf.2012/HintsForSimplePlotter.pdf">ヒント</a>)]
<!--                [<a href="2012/pdf.2012/Exercises/SimpleSquareDrawer.pdf">課題</a>]-->
                <br/>
                [
                <a href="javasrc/SampleGUI/shapeSamples/ShapeSamplesMain.java">shapeSamples/ShapeSamplesMain.java</a>
                <a href="javasrc/SampleGUI/shapeSamples/ShapeSamplesMain.form">shapeSamples/ShapeSamplesMain.form</a>
                <a href="javasrc/SampleGUI/shapeSamples/DrawPanel.java">shapeSamples/DrawPanel.java</a>
                <a href="javasrc/SampleGUI/shapeSamples/DrawPanel.form">shapeSamples/DrawPanel.form</a>
                <a href="javasrc/SampleGUI/simpleDrawer/SimpleDrawerMain.java">simpleDrawer/SimpleDrawerMain.java</a>
                <a href="javasrc/SampleGUI/simpleDrawer/SimpleDrawerMain.form">simpleDrawer/SimpleDrawerMain.form</a>
                <a href="javasrc/SampleGUI/simpleDrawer/DrawPanel.java">simpleDrawer/DrawPanel.java</a>
                <a href="javasrc/SampleGUI/simpleDrawer/DrawPanel.form">simpleDrawer/DrawPanel.form</a>
                ]<br/>
<!--                [課題コード
                <a href="javasrc/SampleGUI/simpleSquareDrawer/SimpleSquareDrawerMain.java"> SimpleSquareDrawerMain.java</a>
                <a href="javasrc/SampleGUI/simpleSquareDrawer/SimpleSquareDrawerMain.form"> SimpleSquareDrawerMain.form</a>
                <a href="javasrc/SampleGUI/simpleSquareDrawer/DrawPanel.java">DrawPanel.java</a>
                <a href="javasrc/SampleGUI/simpleSquareDrawer/DrawPanel.form">DrawPanel.form</a>
                <a href="javasrc/SampleGUI/simpleSquareDrawer/MyShape.java">MyShape.java</a>
                ]--></li>
                <li><a href="2012/pdf.2012/RandomWalk.pdf">例：酔歩</a></li>
                <li><a href="2012/pdf.2012/CMOV.pdf">
                例：結合写像型最適速度交通流モデルのシミュレーション</a>
                [<a href="javasrc/CMOV.tar.gz">ソースコード</a>]</li>
                <li><a href="2012/pdf.2012/SimpleRandomWalk.pdf">
                例：簡単な酔歩シミュレーション2</a>
                [<a href="javasrc/SimpleRandomWalk.tar.gz">ソースコード</a>]
                </li>
                <li><a href="2012/pdf.2012/DB.pdf">データベースの利用</a>
                [<a href="javasrc/DBSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2012/pdf.2012/XML.pdf">XMLの利用</a>
                [<a href="javasrc/XMLSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2012/pdf.2012/DB.pdf">データベースの利用</a>
                [<a href="javasrc/DBSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2012/pdf.2012/Servlet.pdf">サーブレット</a>
                [<a href="javasrc/ServletSample.tar.gz">ソースコード</a>]</li>
                <li><a href="2012/pdf.2012/summary.pdf">まとめ</a></li>
            </ul>
        </div>
    </Section>
    <Section Title="レポート課題">
        <div>
          <ul>
            <li><a href="Reports/2010.pdf">2010年度課題</a></li>
            <li><a href="Reports/2008.pdf">2008年度課題</a></li>
          </ul>
        </div>
    </Section>
</Jarticle>
